Dev
Xxx6ss/techno_park pull request #1
Opened 2020-03-18 10:31 UTC by Xxx6ss

2020-03-18 19:27 UTC, a-badin reviewed
Используем С++ везде где это возможно. Еще раз разбираемся с пайпами и зачем они нужны

2020-03-18 19:27 UTC, a-badin commented on include/process.h
> +#include <stdio.h>
Для объявления Process почти все эти заголовки не нужны. Если их не добавлять, проект будет быстрее компилироваться.

2020-03-18 19:27 UTC, a-badin commented on include/process.h
> +    int pipefd_1[2];
После выхода из констуктора 2 дескриптора станут не нужны и мы их можем не хранить

2020-03-18 19:27 UTC, a-badin commented on src/main.cpp
> +#include "/Users/andrewkireev/CLionProjects/Process/include/process.h"
У меня нет ни макбука, ни пользователя andrewkireev, ни CLion, как бы мне собрать ваш проект.

2020-03-18 19:27 UTC, a-badin commented on src/main.cpp
> +        char echo[] = "/home/CLionProjects/echo/echo";
Тут нет ошибки, ваш код запускается?

2020-03-18 19:27 UTC, a-badin commented on src/main.cpp
> +        process.write("Privet", 6);
write не гарантирует, что отправит столько байт, сколько указано, Он может отправить только Pri.
Нужно писать в цикле со счетчком

2020-03-18 19:27 UTC, a-badin commented on src/process.cpp
> +    if(pipe(pipefd_2)!=0) {
pipefd_1 останется открытым, если будет ошибка

2020-03-18 19:27 UTC, a-badin commented on src/process.cpp
> +            child_pid = getpid();
Когда форк пишет в память родителя происходит copy-on-write, у родителя child_pid не изменится.

2020-03-18 19:27 UTC, a-badin commented on src/process.cpp
> +            dup2(pipefd_1[1],1);
Есть константы STDIN_FILENO и STDOUT_FILENO будет читабельнее

2020-03-18 19:27 UTC, a-badin commented on src/process.cpp
> +            execl(path.c_str(),"1");
exec может выдать ошибку, первый аргумент должен именем файла.  Как-то странно навязывать любому процессу только один аргумент 1

2020-03-18 19:27 UTC, a-badin commented on src/process.cpp
> +            dup2(pipefd_2[1], 1);
Задание не подразумевало менять ввод/вывод у родительского процесса тоже

2020-03-18 19:27 UTC, a-badin commented on src/process.cpp
> +    kill(child_pid, SIGCHLD);
id дочернего процесса лежит в pid

2020-03-18 19:27 UTC, a-badin commented on src/process.cpp
> +    size_t writenByts = ::write(STDOUT_FILENO, data, len);
А зачем нам нужны были pipe, если мы можем просто писать в свой STDIN/STDOUT

2020-03-18 19:27 UTC, a-badin commented on src/process.cpp
> +    ::write(STDOUT_FILENO,data, len);
С точки зрения пользователя класса Process, write и writeExact почти ничем не отличаются
write не гарантирует доставку len, он может доставить только часть

2020-03-19 18:25 UTC, Xxx6ss commented
Исправил почти все замечания

2020-03-21 10:52 UTC, a-badin requested changes
Заменяем выводы на cout/cerr. Удаляем комментарии не по делу. Еще раз проверяем какие методы могут вернуть ошибки и кидаем на них исключения. Программу у меня запустить не удалось

2020-03-21 10:52 UTC, a-badin commented on include/process.h
> +        //int pipefd_1[2];
коммент можно вытереть

2020-03-21 10:52 UTC, a-badin commented on src/main.cpp
> +#include "../include/process.h"
Опять не попали, сведите так, чтобы было "process.h"

2020-03-21 10:52 UTC, a-badin commented on src/process.cpp
> +            throw "Ошибка создания дочернего процесса";
никогда не кидайте типы отличные от std::exception. Рантайм С++ имеет свою логику обработки исключений, в случае если его никто не поймал и оно вылетело за пределы int main. Но для этого исключение должно наследоваться от std::exception

2020-03-21 10:52 UTC, a-badin commented on src/process.cpp
> +        pipe(pipefd_1);
при создании пайпа может возникнуть ошибка

2020-03-21 10:52 UTC, a-badin commented on src/process.cpp
> +            throw "Ошибка создания дочернего процесса";
В случае ошибок открытые пайпы нужно закрыть. Воспользуйтесь, например, классом RAII из лекции 2

2020-03-21 10:52 UTC, a-badin commented on src/process.cpp
> +            stdout_ = pipefd_1[1];
зачем хранить stdout_, когда доч процесс дойдет до execl он вычистит всю память свою память

2020-03-21 10:52 UTC, a-badin commented on src/process.cpp
> +            ::close(pipefd_2[1]);
закрыты не все пайпы, некоторые утекли

2020-03-21 10:52 UTC, a-badin commented on src/process.cpp
> +            fprintf(stderr, "Child PID: %i\n", getpid());
пользуйтесь с++

2020-03-21 10:52 UTC, a-badin commented on src/process.cpp
> +            execl(path.c_str(), path.c_str(), NULL);
execl может выдать ошибку

2020-03-21 16:07 UTC, Xxx6ss commented on include/process.h
> +        //int pipefd_1[2];
Подтер

2020-03-21 16:07 UTC, Xxx6ss commented on src/main.cpp
> +#include "../include/process.h"
Исправил

2020-03-21 16:07 UTC, Xxx6ss commented on src/process.cpp
> +            throw "Ошибка создания дочернего процесса";
Теперь кидаю std::runtime_error

2020-03-21 16:07 UTC, Xxx6ss commented on src/process.cpp
> +        pipe(pipefd_1);
Кидаю исключение при ошибке

2020-03-21 16:07 UTC, Xxx6ss commented on src/process.cpp
> +            throw "Ошибка создания дочернего процесса";
При ошибки создания второго пайпа закрываю первый и кидаю исключение

2020-03-21 16:07 UTC, Xxx6ss commented on src/process.cpp
> +            stdout_ = pipefd_1[1];
Убрал

2020-03-21 16:07 UTC, Xxx6ss commented on src/process.cpp
> +            ::close(pipefd_2[1]);
Закрыл остальные

2020-03-21 16:08 UTC, Xxx6ss commented on src/process.cpp
> +            fprintf(stderr, "Child PID: %i\n", getpid());
Исправил на std::cout

2020-03-21 16:08 UTC, Xxx6ss commented on src/process.cpp
> +            execl(path.c_str(), path.c_str(), NULL);
Кидаю исключение

2020-03-26 08:30 UTC, a-badin requested changes

2020-03-26 08:30 UTC, a-badin commented on src/process.cpp
> +            wr += static_cast<std::size_t>(::write(stdout_, static_cast<const char*>(data) + wr, len - wr));
У вас же есть удобный собственный метод Process::write

2020-03-26 08:30 UTC, a-badin commented on src/process.cpp
> +            wr += static_cast<std::size_t>(::write(stdout_, static_cast<const char*>(data) + wr, len - wr));
Write может вернуть -1, что означает ошибку, вы ее кастанете к безнаковому числу

2020-03-26 08:30 UTC, a-badin commented on src/process.cpp
> +            std::cerr << "Метод ничего не смог прочитать" << std::endl;
Если read вернет 0, это не ошибка - просто конец ввода данных.
Если read вернет -1, кидайте искючение - программа не сможет обработать ошибку по выводу в лог

2020-03-26 08:30 UTC, a-badin commented on src/process.cpp
> +            std::cerr << "Метод ничего не смог прочитать" << std::endl;
В момент когда read вернет 0 вы устанавливаете флаг, что in_is_readable = false

2020-03-26 08:30 UTC, a-badin commented on src/process.cpp
> +        out_is_readable = false;
out_is_readable всегда false. Out - вывод, в него можно только писать. Вы можете без последствий удалить этот флаг

2020-03-26 08:30 UTC, a-badin commented on src/main.cpp
> +    process::Process pr("");
Где программа, которую будем запускать

2020-03-26 08:30 UTC, a-badin commented on src/main.cpp
> +    const char data[6] = {'p', 'r', 'i', 'v', 'e', 't'};
const char *data = "privet";

2020-03-26 08:30 UTC, a-badin commented on src/main.cpp
> +    pr.write(data,6 );
Я уже писал, что write не дает гарантий, что он считает 6 байт за один вызов.
Воспользуйтесь методом writeExact

2020-03-26 08:30 UTC, a-badin commented on src/main.cpp
> +        std::cout << new_data[i];
cout умеет выводить строки

2020-03-26 08:30 UTC, a-badin commented on src/main.cpp
> +    char new_data[6];
рекомендую std::string, писать в его new_data.data()

2020-03-26 08:30 UTC, a-badin commented on src/process.cpp
> +        waitpid(pid, 0, WUNTRACED);
Посмотрите в man какие заголовки нужно подключить

2020-03-26 08:30 UTC, a-badin commented on src/process.cpp
> +            throw std::runtime_error(std::strerror(errno));
Посмотрите в cppreferece какие заголовки надо подключить для strerror

2020-03-26 19:01 UTC, Xxx6ss commented on src/process.cpp
> +            wr += static_cast<std::size_t>(::write(stdout_, static_cast<const char*>(data) + wr, len - wr));
+

2020-03-26 19:01 UTC, Xxx6ss commented on src/process.cpp
> +            std::cerr << "Метод ничего не смог прочитать" << std::endl;
+

2020-03-26 19:01 UTC, Xxx6ss commented on src/process.cpp
> +        out_is_readable = false;
+

2020-03-26 19:01 UTC, Xxx6ss commented on src/main.cpp
> +    process::Process pr("");
Запускаю /bin/pwd

2020-03-26 19:01 UTC, Xxx6ss commented on src/main.cpp
> +    const char data[6] = {'p', 'r', 'i', 'v', 'e', 't'};
+

2020-03-26 19:02 UTC, Xxx6ss commented on src/main.cpp
> +    pr.write(data,6 );
+

2020-03-26 19:02 UTC, Xxx6ss commented on src/main.cpp
> +        std::cout << new_data[i];
Делаю из чарового массива строку и уже ее вывожу

2020-03-26 19:02 UTC, Xxx6ss commented on src/main.cpp
> +    char new_data[6];
Если использовать std::string new_data.data() или new_data().c_str(), то у меня выдает ошибку, тк в функции у нас void *data, поэтому использую чаровый массив и потом его в строку преобразую для вывода

2020-03-26 19:02 UTC, Xxx6ss commented on src/process.cpp
> +        waitpid(pid, 0, WUNTRACED);
Подключил для kill() <csignal>

2020-03-26 19:02 UTC, Xxx6ss commented on src/process.cpp
> +            throw std::runtime_error(std::strerror(errno));
Подключил <cstring>

2020-03-26 19:21 UTC, Xxx6ss commented on src/process.cpp
> +        waitpid(pid, 0, WUNTRACED);
<csignal>

2020-03-26 19:21 UTC, Xxx6ss commented on src/process.cpp
> +        waitpid(pid, 0, WUNTRACED);
csignal

2020-03-26 19:22 UTC, Xxx6ss commented on src/process.cpp
> +            throw std::runtime_error(std::strerror(errno));
cstring

2020-03-28 18:44 UTC, a-badin requested changes

2020-03-28 18:44 UTC, a-badin commented on CMakeLists.txt
> +set(SOURCE_LIB "${PROJECT_SOURCE_DIR}/src/process.cpp" "${PROJECT_SOURCE_DIR}/include/process.h")
Зачем нам добавлять заголовочный файл как исходник?

2020-03-28 18:44 UTC, a-badin commented on CMakeLists.txt
> +set(SOURCE_EXE "${PROJECT_SOURCE_DIR}/src/main.cpp")
Мы можем не писать PROJECT_SOURCE_DIR, пути в cmake идут относительно расположения самого файла CMakeLists.txt

2020-03-28 18:44 UTC, a-badin commented on CMakeLists.txt
> +target_include_directories(main PUBLIC ./include)
Это можно не писать, ./include подключится автоматически так как вы поставили PUBLIC на библиотеке и слинковали эту библиотеку с main

2020-03-28 18:44 UTC, a-badin commented on src/process.cpp
> +        return static_cast<size_t>(bytes);
Если write вернет -1, статик каст сделает его большим положительным числом.
Сравнение на -1 сработает, а сравнение на < 0 нет. Кидайте исключение если write вернул -1

2020-03-28 18:44 UTC, a-badin commented on src/process.cpp
> +            wr += static_cast<std::size_t>(write(static_cast<const char*>(data) + wr, len - wr));
когда вы поменяете свой метод write вы сможете здесь куда удобнее работать только с unsigned

2020-03-28 18:44 UTC, a-badin commented on src/process.cpp
> +        fflush(stdout);
Зачем здесь это?

2020-03-28 18:44 UTC, a-badin commented on src/process.cpp
> +            std::cerr << "Метод ничего не смог прочитать" << std::endl;
Почему cerr? Как обработать эту ошибку?

2020-03-28 18:44 UTC, a-badin commented on src/main.cpp
> +    const char *data = "privet";
Почему bin/pwd? Он не слушает stdin, как вы проверете что ваш Process работает? Принимайте процесс параметром из argv

2020-03-28 18:44 UTC, a-badin commented on src/main.cpp
> +    pr.readExact(new_data, 50);
А если pwd вернет меньше 50 байт?
Я думаю readExact вам не подходит, потому что вы не знаете и не можете знать сколько байт вам вернет программа

2020-03-28 18:44 UTC, a-badin commented on src/process.cpp
> +            if (read == last_it) {
Если вы прибавляете вывод в переменную, вы не поймаете момент когда read вернет -1 или 0

2020-03-28 18:44 UTC, a-badin commented on src/process.cpp
> +        waitpid(pid, nullptr, WUNTRACED);
ругается на отсутствие заголовка

2020-03-28 18:44 UTC, a-badin commented on src/process.cpp
> +        ::close(stdin_);
у вас есть метод closeStdin не повторяйте код

2020-03-28 18:44 UTC, a-badin commented on src/process.cpp
> +        ::close(stdout_);
close может вернуть ошибку, лучше её не игнорировать

2020-03-29 16:17 UTC, Xxx6ss commented on CMakeLists.txt
> +set(SOURCE_LIB "${PROJECT_SOURCE_DIR}/src/process.cpp" "${PROJECT_SOURCE_DIR}/include/process.h")
Подправил

2020-03-29 16:17 UTC, Xxx6ss commented on CMakeLists.txt
> +set(SOURCE_EXE "${PROJECT_SOURCE_DIR}/src/main.cpp")
+

2020-03-29 16:17 UTC, Xxx6ss commented on CMakeLists.txt
> +target_include_directories(main PUBLIC ./include)
+

2020-03-29 16:17 UTC, Xxx6ss commented on src/process.cpp
> +        return static_cast<size_t>(bytes);
+

2020-03-29 16:17 UTC, Xxx6ss commented on src/process.cpp
> +            wr += static_cast<std::size_t>(write(static_cast<const char*>(data) + wr, len - wr));
Убрал static_cast <std::size_t>

2020-03-29 16:18 UTC, Xxx6ss commented on src/main.cpp
> +    pr.readExact(new_data, 50);
Поменял на read

2020-03-29 16:18 UTC, Xxx6ss commented on src/process.cpp
> +            if (read == last_it) {
+

2020-03-29 16:18 UTC, Xxx6ss commented on src/process.cpp
> +        waitpid(pid, nullptr, WUNTRACED);
Добавил #include  sys/wait.h

2020-03-29 16:18 UTC, Xxx6ss commented on src/process.cpp
> +        ::close(stdin_);
+

2020-03-29 16:18 UTC, Xxx6ss commented on src/process.cpp
> +        ::close(stdout_);
Кидаю исключение

2020-03-30 09:22 UTC, a-badin commented on src/main.cpp
> +    pr.writeExact(data, 50 );
У вас размер data 6 байт,  дальше вы лезете в адреса памяти, которая вообще не факт, что доступна вашему процессу. Если вы пользуетесь C, его сырыми указателями и буферами с фиксированным размером, значит вам нужно быть очень внимательным. Я повторяю вам то, что написал еще в первом ревью - пользуйтесь С++.
Возьмите std::string data = "privet"; Отправьте data.data() и размер data.size()

2020-03-30 09:22 UTC, a-badin commented on src/main.cpp
> +    pr.read(new_data, 50);
Ходим кругами, у вас нет гарантий, что read запишет 50 байт за 1 вызов.
И вы не знаете сколько байт вам передаст программа. Единственное на что вы можете положиться это на то, что когда Process закроет свой поток вывода(вернет 0), он уже точно ничего не передаст и его вывод закончен.
Значит вы заводите какой-нибудь буфер(new_data, например, но лучше std::string), читаете в него в цикле по максимальному числу байт (размер вашего буфера) и выводите в cout, чистите буфер и снова встаете на чтение. До тех пор пока read не вернет 0, вот тогда вы можете выходить из программы.

2020-03-30 09:22 UTC, a-badin commented on src/main.cpp
> +    process::Process proc(argv[1]);
Где проверка на число аргументов, что этот процесс делает?

2020-03-30 09:22 UTC, a-badin commented on src/main.cpp
> +    char new_data[6];
любой указатель преобразуется к void * сам автоматически.
Если у вас ругается что data() - это const char* , значит вам нужно включить C++11 или больше. Скорее всего у вас старая версия компилятора, добавьте в CMakeLists.txt после cmake_minimum_required(...) set(CMAKE_CXX_STANDARD 17)

2020-03-30 09:26 UTC, a-badin requested changes

2020-03-30 09:26 UTC, a-badin commented on src/process.cpp
> +        close();
Ваш констурктор помечен как noexcept, а close теперь кидает исключение.
Ваша программа завершится с ошибкой, если close не сможет закрыться.
Мы обсуждали этот момент в чатике, вам нужно ловить исключение от close и игнорировать его

2020-04-01 11:45 UTC, Xxx6ss commented on src/main.cpp
> +    process::Process proc(argv[1]);
Проверку на число аргументов добавил, процесс вызывает /bin/cat

2020-04-01 11:45 UTC, Xxx6ss commented on src/main.cpp
> +    pr.read(new_data, 50);
Я так понимаю, в раньше я не мог использовать readExact, тк подменял программу на bin/pwd, но теперь записываю определенное количество байт, которое точно есть в строке, поэтому могу использовать readExact

2020-04-01 11:45 UTC, Xxx6ss commented on src/main.cpp
> +    pr.writeExact(data, 50 );
добавил метод out.resize(in.size()), с ним заработало

2020-04-01 11:45 UTC, Xxx6ss commented on src/process.cpp
> +        close();
+

2020-04-01 15:24 UTC, a-badin requested changes

2020-04-01 15:24 UTC, a-badin commented on src/process.cpp
> +            in_is_readable = true;
Уже писал, у вас у child своя копия памяти, любое изменение из child не видно в parent.
in_is_readable останется у parent в прежнем значении, изменять in_is_readable здесь нет смысла

2020-04-01 15:24 UTC, a-badin commented on src/process.cpp
> +            kill(pid, SIGCHLD);
Почему SIGCHLD?

2020-04-01 15:24 UTC, a-badin commented on src/process.cpp
> +        if(::close(stdout_) < 0){
1. Вызываем у Process close()
2. Открываем какой-нибудь файл
3. Файл получает только что освобожденный дескриптор stdout_
4. Process теперь пишет в файл
5. При уничтожении Process закроет абсолютно чужой файл

2020-04-01 15:24 UTC, a-badin commented on src/process.cpp
> +        ssize_t wr = 0, last_it = 0;
wr знаковый, а len беззнаковый

2020-04-01 18:53 UTC, Xxx6ss commented on src/process.cpp
> +            kill(pid, SIGCHLD);
Поменял на SIGTERM

2020-04-01 18:54 UTC, Xxx6ss commented on src/process.cpp
> +        ssize_t wr = 0, last_it = 0;
привожу wr к size_t

2020-04-01 18:54 UTC, Xxx6ss commented on src/process.cpp
> +            in_is_readable = true;
удалил

2020-04-01 18:59 UTC, Xxx6ss commented on src/process.cpp
> +        if(::close(stdout_) < 0){
Мне кажется, это можно решить, добавив флаг out_is_writable, тогда в close можно будет сделать out_is_writable = false и проверку на то, равен ли этот флаг false, если равен, то close для этого дескриптора вызываться не будет. Тогда процесс не сможет писать в не относящийся к нему файл и не сможет уничтожить не его дескриптор. Только раньше вы сказали, что этот флаг не нужен(

2020-04-03 14:33 UTC, a-badin requested changes

2020-04-03 14:33 UTC, a-badin commented on CMakeLists.txt
> +add_executable(echo ${ECHO_PROC})
А файл src/echo.cpp вы удалили

2020-04-03 14:33 UTC, a-badin commented on src/process.cpp
> +        ssize_t wr = 0, last_it = 0;
Зачем? У вас len беззнаковый, write беззнаковый, у вас тут нигде не может появиться отрицательное число. Зачем вам ssize_t?

2020-04-04 12:46 UTC, a-badin approved these changes

2020-04-04 12:46 UTC, a-badin commented on src/main.cpp
> +            while (to_read != 0 && (byte = proc.read(out.data(), 4096)) > 0 && proc.isReadable()) {
Вот это очень сложно читать

2020-04-04 12:46 UTC, a-badin commented on src/main.cpp
> +                std::cout << out << std::endl;
out надо сделать resize до byte

2020-04-04 12:46 UTC, a-badin commented on src/process.cpp
> +        if(::close(stdout_) < 0){
Вот тут можно было поставить проверку на то, что stdout_ не -1 , а то даже когда все хорошо у вас всплывает Ошибка закрытия дескриптора

2020-04-04 12:48 UTC, merged