Hw 2
Xxx6ss/techno_park pull request #2
Opened 2020-03-27 11:20 UTC by Xxx6ss

2020-03-31 21:26 UTC, smirnov-vs requested changes

2020-03-31 21:26 UTC, smirnov-vs commented on src/main.cpp
> -        Process process(echo);
почему тут был процесс?
дз не пересекаются между собой

2020-03-31 21:26 UTC, smirnov-vs commented on include/BadLog.h
> +        BadLog(std::string& msg) : str(std::move(msg)){}
тогда надо по значению передавать, забирать вот так просто чужие строки нехорошо

2020-03-31 21:26 UTC, smirnov-vs commented on include/process.h
> -#endif //PROCESS_PROCESS_H
так и тянет не проверяя, отправить ПР переделывать)

2020-03-31 21:26 UTC, smirnov-vs commented on lib/FileLogger.cpp
> +    FileLogger::FileLogger() : file_("Log.txt") {
в чем практический смысл такого конструктора?)

2020-03-31 21:26 UTC, smirnov-vs commented on lib/FileLogger.cpp
> +            throw std::runtime_error("Ошибка создания файла");
русские буквы надо поправить

2020-03-31 22:38 UTC, Xxx6ss commented on src/main.cpp
> -        Process process(echo);
Ветку для второго дз случайно сделал базируясь на ветке от первого дз, а не от пустого мастера((, поэтому там первоначально были эти файлы

2020-04-01 08:45 UTC, Xxx6ss commented on lib/FileLogger.cpp
> +    FileLogger::FileLogger() : file_("Log.txt") {
Если не передали никакого файла, то он создает Log.txt и пишет логи в него

2020-04-01 08:45 UTC, Xxx6ss commented on include/BadLog.h
> +        BadLog(std::string& msg) : str(std::move(msg)){}
Убрал ссылку

2020-04-01 08:49 UTC, Xxx6ss commented on lib/FileLogger.cpp
> +            throw std::runtime_error("Ошибка создания файла");
Поменял на английский

2020-04-01 09:13 UTC, Xxx6ss commented
Не понимаю, как поправить этот пулл реквест. Просто я первым коммитом в мастер залил уже готовое первое дз, потом мне сказали, что нужно удалить, удалил, но  все ветки строятся на мастере, и в них есть два коммита с добавлением и удалением первого дз. Создал полностью новую ветку, не основанную на мастере, но не могу создать pull request, тк нет ничего общего с мастером, так что не очь понимаю как решить эту проблему.

2020-04-01 09:17 UTC, Xxx6ss commented
Остальные замечания поправил

2020-04-05 16:36 UTC, smirnov-vs commented
алгоритм всегда один
становимся на мастер, создаем новую ветку, коммитим изменения, делаем ПР

2020-04-05 16:37 UTC, smirnov-vs commented
оформи текущую версию верно, посмотрю еще раз все ли верно в коде и закроем

2020-04-09 07:10 UTC, closed without merging