Hw 3
Xxx6ss/techno_park pull request #3
Opened 2020-04-03 11:27 UTC by Xxx6ss

2020-04-07 08:17 UTC, a-badin requested changes
Сделайте свой класс на исключения

2020-04-07 08:17 UTC, a-badin commented on CMakeLists.txt
> +set(CLIENT "src/test_client.cpp")
кавычки можно не писать, если нет пробелов

2020-04-07 08:17 UTC, a-badin commented on CMakeLists.txt
> +target_link_libraries(server PUBLIC ${LIB_NAME})
У вас server это экзешник, а не либа. Значит server не будет ни к чему линковаться как зависимость (к нему будут, другие библиотеки) значит PUBLIC или PRIVATE можно не писать

2020-04-07 08:17 UTC, a-badin commented on CMakeLists.txt
> +target_include_directories(server PUBLIC ${LIB_DIR})
У вас в директории lib есть какие-то заголовочные файлы? Кажется нет

2020-04-07 08:17 UTC, a-badin commented on include/Connection.h
> +        Connection(std::string ip, uint16_t port);
const

2020-04-07 08:17 UTC, a-badin commented on include/Connection.h
> +        Connection(int& sock_fd, const sockaddr_in& sock_info);
int обычно передают по значению

2020-04-07 08:17 UTC, a-badin commented on include/Connection.h
> +        std::string dst_addr;
дэш

2020-04-07 08:17 UTC, a-badin commented on include/Connection.h
> +        uint16_t dst_port;
дэш

2020-04-07 08:17 UTC, a-badin commented on lib/CMakeLists.txt
> +set(LIB ${LIB_DIR}/Connection.cpp
у вас же LIB_DIR это текущая директория, напишите просто Connection.cpp
Ну весь cmake сделан, чтобы вам было легче, а не труднее

2020-04-07 08:17 UTC, a-badin commented on lib/Connection.cpp
> +        connect(dst_addr, port);
Нарушаем базовую гарантию безопасности исключений

2020-04-07 08:17 UTC, a-badin commented on lib/Connection.cpp
> +        sockfd = -1;
Это лишнее. Деструктор вызывается только тогда, когда был успешно завершен констурктор. Если конструктор не заершился, значит объект не создался, значит деструктор не вызовется

2020-04-07 08:17 UTC, a-badin commented on lib/Connection.cpp
> +        if(::close(sockfd_) < 0){
Выставляйте sock_fd в -1 и проверяйте. Вы можете закрыть какой-нибудь случайный файл.
Говорили об этом в 1 ом домашнем заданий, говорили об этом в предыдущей лекции

2020-04-07 08:17 UTC, a-badin commented on include/Connection.h
> +        void send_size(const size_t& data);
Я бы сказал, что это уже детали вашего протокола передачи, и к Connection.h не относится.

2020-04-07 08:17 UTC, a-badin commented on include/Connection.h
> +        Connection(int& sock_fd, const sockaddr_in& sock_info);
Рекомендую положить этот констурктор в private, чтобы пользователь не мог сконструировать ваш класс неправильно. добавьте метод Server::accept в friendы класса
следующим образом:
```
Connection(open("123.txt", O_RDONLY), sockaddr_in{});
Connection(1, sockaddr_in{});
```

2020-04-07 08:17 UTC, a-badin commented on include/Server.h
> +        bool server_stat = false;
дэш

2020-04-07 08:17 UTC, a-badin commented on lib/Connection.cpp
> +        is_open_ = true;
нарушение базовой безопасности исключений

2020-04-07 08:17 UTC, a-badin commented on lib/Connection.cpp
> +        if(::connect(sockfd_, (struct sockaddr *)&addr_, sizeof(addr_)) < 0){
а закрыть sockfd_. Полагаться на то, что пользователь не забудет вызвать close очень рисковано.
Пользуйтесь приницпом: должно быть легко пользоваться вашими методами правильно, и тяжело неправильно.

2020-04-07 08:17 UTC, a-badin commented on lib/Server.cpp
> +            throw std::runtime_error("Ошибка создание сокета");
нарушение базовой гарантии

2020-04-07 08:17 UTC, a-badin commented on lib/Server.cpp
> +        Server(ip, port);
Я бы скорее сделал наоборот, в конструкторе звал open. В open логика вполне ограниченная, а вот что там делает или будет делать класс(или его наследники) в конструкторе не понятно

2020-04-07 08:17 UTC, a-badin commented on lib/Server.cpp
> +        if (server_stat) {
Можем сами закрыть. Скорее всего, если пользователь вызывает open на уже открытом соединении, значит он так хочет и предыдущее ему уже не интересно. А с такой логикой, вы как будто хотите его подловить на ошибке, как бы говоря "ААаа забыл соединение закрыть"

2020-04-07 08:17 UTC, a-badin commented on lib/Server.cpp
> +        max_connection_ = num_connections;
Кажется можно сразу выставить через listen, если соединение открыто конечно

2020-04-07 08:17 UTC, a-badin commented on lib/Server.cpp
> +        if(::close(listenfd_) < 0){
проверяем, что не закрываем кого-то другого

2020-04-07 08:17 UTC, a-badin commented on lib/Server.cpp
> +            throw std::runtime_error("Ошибка закрытия сервера");
Ну не является закрытие закрытого ошибкой
Представьте такой код
```
Server s{...};
s.read(...);
s.close();
```
Получается мы не можем так написать не получая сообщения об ошибках  в cerr

2020-04-08 15:05 UTC, Xxx6ss commented on CMakeLists.txt
> +set(CLIENT "src/test_client.cpp")
+

2020-04-08 15:05 UTC, Xxx6ss commented on CMakeLists.txt
> +target_link_libraries(server PUBLIC ${LIB_NAME})
+

2020-04-08 15:05 UTC, Xxx6ss commented on CMakeLists.txt
> +target_include_directories(server PUBLIC ${LIB_DIR})
+

2020-04-08 15:05 UTC, Xxx6ss commented on include/Connection.h
> +        Connection(std::string ip, uint16_t port);
+

2020-04-08 15:05 UTC, Xxx6ss commented on include/Connection.h
> +        Connection(int& sock_fd, const sockaddr_in& sock_info);
+

2020-04-08 15:05 UTC, Xxx6ss commented on include/Connection.h
> +        std::string dst_addr;
+

2020-04-08 15:05 UTC, Xxx6ss commented on include/Connection.h
> +        uint16_t dst_port;
+

2020-04-08 15:05 UTC, Xxx6ss commented on lib/CMakeLists.txt
> +set(LIB ${LIB_DIR}/Connection.cpp
+

2020-04-08 15:05 UTC, Xxx6ss commented on lib/Connection.cpp
> +        connect(dst_addr, port);
+

2020-04-08 15:05 UTC, Xxx6ss commented on lib/Connection.cpp
> +        sockfd = -1;
+

2020-04-08 15:05 UTC, Xxx6ss commented on lib/Connection.cpp
> +        if(::close(sockfd_) < 0){
Поставил проверку на sock_fd != -1

2020-04-08 15:06 UTC, Xxx6ss commented on include/Connection.h
> +        Connection(int& sock_fd, const sockaddr_in& sock_info);
+

2020-04-08 15:06 UTC, Xxx6ss commented on include/Server.h
> +        bool server_stat = false;
+

2020-04-08 15:06 UTC, Xxx6ss commented on lib/Connection.cpp
> +        is_open_ = true;
Переместил в конец метода, после выброса исключения

2020-04-08 15:06 UTC, Xxx6ss commented on lib/Connection.cpp
> +        if(::connect(sockfd_, (struct sockaddr *)&addr_, sizeof(addr_)) < 0){
добавил close()

2020-04-08 15:06 UTC, Xxx6ss commented on lib/Server.cpp
> +            throw std::runtime_error("Ошибка создание сокета");
А почем тут нарушение? У меня будет сгенерировано исключение только в том случае, если listenfd_ будет равно -1, и ничего не нужно будет закрывать, и переменной server_stat_ у меня присваивается false в конце конструктора

2020-04-08 15:06 UTC, Xxx6ss commented on lib/Server.cpp
> +        Server(ip, port);
перенес всю логики в open

2020-04-08 15:06 UTC, Xxx6ss commented on lib/Server.cpp
> +        if (server_stat) {
убрал

2020-04-08 15:06 UTC, Xxx6ss commented on lib/Server.cpp
> +        max_connection_ = num_connections;
поместил listen в set_max_connection

2020-04-08 15:06 UTC, Xxx6ss commented on lib/Server.cpp
> +        if(::close(listenfd_) < 0){
+

2020-04-08 15:06 UTC, Xxx6ss commented on lib/Server.cpp
> +            throw std::runtime_error("Ошибка закрытия сервера");
добавил перед этим проверку на listenfd_ == -1 и server_stat_ == false, и если что-то равно, то ::Close() вызываться не будет

2020-04-18 09:10 UTC, a-badin commented on HW_3/lib/Connection.cpp
> +            is_open_ = false;
давайте определимся, пусть будет флаг is_readable, который означает, что еще можно читать из соединения. Его выставляем когда ловим 0 из read

2020-04-18 09:10 UTC, a-badin commented on HW_3/lib/Connection.cpp
> +        return is_open_;
Тогда вместо того, чтобы заводить еще флаг на проверку открыто ли соединение, будет проверять значние дескриптора -1 или нет

2020-04-18 09:10 UTC, a-badin commented on HW_3/lib/Connection.cpp
> +                throw TcpException("close server failed");
После закрытия, нужно перевести sockfd_ в невалидное состоние, чтобы не начать работать с чужим дескриптором

2020-04-18 09:10 UTC, a-badin commented on lib/Server.cpp
> +            throw std::runtime_error("Ошибка создание сокета");
Да, тут я не прав

2020-04-18 09:15 UTC, a-badin requested changes
Добавьте установку в -1 и для соединения и для сервера, если получится избавиться от флага _is_opened будет даже лучше

2020-04-18 10:25 UTC, Xxx6ss commented on HW_3/lib/Connection.cpp
> +                throw TcpException("close server failed");
перевожу, от флагов в в соединении и сервере избавился, определяю по состоянию

2020-04-18 10:25 UTC, Xxx6ss commented on HW_3/lib/Connection.cpp
> +        return is_open_;
+

2020-04-18 10:25 UTC, Xxx6ss commented on HW_3/lib/Connection.cpp
> +            is_open_ = false;
добавил такой флаг

2020-04-20 11:48 UTC, a-badin approved these changes
Третья домашняя работа засчитана на 9.
Правьте конфликты и сливайте с мастером

2020-04-20 11:48 UTC, a-badin commented on HW_3/lib/Connection.cpp
> +        is_readable = true;
А это тут причем, как связаны запись и чтение?

2020-04-20 12:52 UTC, merged