adding HW_4
Xxx6ss/techno_park pull request #5
Opened 2020-04-12 18:25 UTC by Xxx6ss

2020-04-15 19:29 UTC, a-badin requested changes
В условии задания было сделать буфферизацию ввода/вывода. Так как за один callback например read, вы можете не прочитать все данные за раз. Постарайтесь добавить эту логику к пятнице

2020-04-15 19:29 UTC, a-badin commented on HW_4/.idea/.name
> +tcp
Добавьте это в .gitignore

2020-04-15 19:29 UTC, a-badin commented on HW_4/include/Server.h
> +               std::function<void(Connection&)> callback_write);
Можно вынести в отдельный using std::function<void(Connection&)>

2020-04-15 19:29 UTC, a-badin commented on HW_4/src/test_server.cpp
> +    } catch (...){
Это что-то нехорошее

2020-04-15 19:29 UTC, a-badin commented on HW_4/src/test_client.cpp
> +    while (!data.empty() || (data == "^D" && con.is_opened()))
Где то я это уже видел
^D это два байта, один ^ другой D, на закрытие ввода это никак не влияет

2020-04-15 19:29 UTC, a-badin commented on HW_4/lib/Server.cpp
> +        listen(listenfd_, max_connection_);
а ошибку обработать

2020-04-15 19:29 UTC, a-badin commented on HW_4/lib/Server.cpp
> +        epoll_ = epoll_create(1);
если вынести во вовременную переменную можно сделать строгую гарантию безопасности

2020-04-15 19:29 UTC, a-badin commented on HW_4/lib/Server.cpp
> +        if(listenfd_ != -1 && !server_stat_) {
Может закрыть дескриптор которым уже не владеем

2020-04-17 13:25 UTC, Xxx6ss commented on HW_4/lib/Server.cpp
> +        epoll_ = epoll_create(1);
вынес

2020-04-17 13:25 UTC, Xxx6ss commented on HW_4/lib/Server.cpp
> +        if(listenfd_ != -1 && !server_stat_) {
так у меня на этот случай он как раз проверяет флаг, если этот дескриптор перестал быть дескриптором сервера, то флаг должен быть = false

2020-04-17 13:25 UTC, Xxx6ss commented on HW_4/lib/Server.cpp
> +        listen(listenfd_, max_connection_);
+

2020-04-17 13:25 UTC, Xxx6ss commented on HW_4/src/test_client.cpp
> +    while (!data.empty() || (data == "^D" && con.is_opened()))
я это в предыдущем дз использовал как флаг окончания ввода у клиента

2020-04-17 13:26 UTC, Xxx6ss commented on HW_4/src/test_server.cpp
> +    } catch (...){
ловлю свой класс исключений

2020-04-17 13:26 UTC, Xxx6ss commented on HW_4/include/Server.h
> +               std::function<void(Connection&)> callback_write);
+

2020-04-18 10:54 UTC, a-badin requested changes

2020-04-18 10:54 UTC, a-badin commented on HW_4/lib/Connection.cpp
> +            if (errno == EINTR) {
Правильно обрабатываем EINTR

2020-04-18 10:54 UTC, a-badin commented on HW_4/lib/Connection.cpp
> +                return -1;
Не возвращаем -1

2020-04-18 10:54 UTC, a-badin commented on HW_4/include/Server.h
> +        bool epoll_stat = false;
не дублируйте состояния, этот флаг повторяется значением сокета listenfd_

2020-04-18 10:54 UTC, a-badin commented on HW_4/include/Server.h
> +        int listenfd_;
рекомендую обернуть оба дексриптора в отдельные RAII объекты

2020-04-18 10:54 UTC, a-badin commented on HW_4/include/Connection.h
> +        int sockfd_;
тоже в RAII, можно совсем простой с int в констукторе и ::close в деструкторе + move

2020-04-18 10:54 UTC, a-badin commented on HW_4/lib/Server.cpp
> +                auto event = events[n].events;
auto

2020-04-18 10:54 UTC, a-badin commented on HW_4/lib/Server.cpp
> +            add_epoll(fd, EPOLLIN);
Почему только EPOLLIN, а если мы только пишем в соединения

2020-04-18 10:54 UTC, a-badin commented on HW_4/lib/Server.cpp
> +            if(::close(fd) < 0) {
лучше пусть fd закроет сам connection, не управляйте ресурсом, которым не владеете
А почему из connects_ его нужно удалить только если close < 0? кажется что connection нужно убрать из map как только мы закрыли соединение

2020-04-18 10:54 UTC, a-badin commented on HW_4/src/test_server.cpp
> +            server.erase_connection(fd);
Сделайте интерфейс принимающий Connection, чтобы не доставать fd

2020-04-18 10:54 UTC, a-badin commented on HW_4/src/test_server.cpp
> +        ssize_t bytes = c.read(v.data(), v.size() + 1);
Почему +1 ? Чтобы получить segfault?

2020-04-18 10:54 UTC, a-badin commented on HW_4/src/test_server.cpp
> +    std::string v;
нужно сделать буфер отдельный на каждое подключение. Очень желательно в библиотеке, а не в колбеке

2020-04-19 10:56 UTC, Xxx6ss commented on HW_4/src/test_server.cpp
> +    std::string v;
храню std::string в каждом соединении

2020-04-19 10:56 UTC, Xxx6ss commented on HW_4/src/test_server.cpp
> +        ssize_t bytes = c.read(v.data(), v.size() + 1);
тут убрал, но без единицы во write вылетает ошибка

2020-04-19 10:56 UTC, Xxx6ss commented on HW_4/src/test_server.cpp
> +            server.erase_connection(fd);
удаляю по соединению

2020-04-19 10:57 UTC, Xxx6ss commented on HW_4/lib/Server.cpp
> +            if(::close(fd) < 0) {
+

2020-04-19 10:57 UTC, Xxx6ss commented on HW_4/lib/Server.cpp
> +            add_epoll(fd, EPOLLIN);
+

2020-04-19 10:57 UTC, Xxx6ss commented on HW_4/lib/Server.cpp
> +                auto event = events[n].events;
+

2020-04-19 10:57 UTC, Xxx6ss commented on HW_4/include/Server.h
> +        int listenfd_;
обернул

2020-04-19 10:57 UTC, Xxx6ss commented on HW_4/include/Server.h
> +        bool epoll_stat = false;
убрали флаг

2020-04-19 10:57 UTC, Xxx6ss commented on HW_4/lib/Connection.cpp
> +                return -1;
кидаю исключение

2020-04-19 10:57 UTC, Xxx6ss commented on HW_4/lib/Connection.cpp
> +            if (errno == EINTR) {
+

2020-04-26 10:32 UTC, a-badin approved these changes

2020-04-26 10:32 UTC, a-badin commented on HW_4/lib/Descriptor.cpp
> +            try{
на самом деле тут вы вполне можете кинуть исключение

2020-04-26 10:33 UTC, merged