HW_5
Xxx6ss/techno_park pull request #6
Opened 2020-04-27 13:24 UTC by Xxx6ss

2020-04-27 18:45 UTC, smirnov-vs requested changes

2020-04-27 18:45 UTC, smirnov-vs commented on HW_5/lib/SharedMap.h
> +            map_ = new (map_) Map{allocator};
allocator_traits

2020-04-27 18:45 UTC, smirnov-vs commented on HW_5/lib/SharedMap.h
> +            map_->~map();
destroy

2020-04-27 18:45 UTC, smirnov-vs commented on HW_5/lib/SharedMap.h
> +            SemaphoreLock lock = SemaphoreLock(sem_);
тип 2 раза

2020-04-27 18:45 UTC, smirnov-vs commented on HW_5/lib/Semaphore.h
> +            allocator_.deallocate(sem_, 1);
деструктор только один раз
проверить

2020-05-15 08:44 UTC, Xxx6ss commented on HW_5/lib/SharedMap.h
> +            SemaphoreLock lock = SemaphoreLock(sem_);
Использую lock_guard

2020-05-15 08:45 UTC, Xxx6ss commented on HW_5/lib/Semaphore.h
> +            allocator_.deallocate(sem_, 1);
Увидел, что он два раза вызывается, использую дефолтный деструктор

2020-05-15 08:46 UTC, Xxx6ss commented on HW_5/lib/SharedMap.h
> +            map_ = new (map_) Map{allocator};
использую std::allocator_traits<Allocator<Map>>::construct

2020-05-15 15:38 UTC, smirnov-vs approved these changes

2020-05-15 15:38 UTC, merged